# Generated by Django 4.1.2 on 2023-08-17 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcare', '0002_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 11, 49, 53, 455263, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medi exam', 'Medical Examination'), ('doctor check', 'Doctor Check'), ('check up', 'Check-Up'), ('result analysis', 'Result Analysis')], max_length=30)),
                ('appointment_date', models.DateTimeField(default=datetime.datetime(2023, 8, 17, 11, 49, 53, 456260, tzinfo=datetime.timezone.utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
