# Generated by Django 4.1.2 on 2023-08-17 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcare', '0006_alter_appointment_appointment_date_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 51, 21, 455663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 51, 21, 454667, tzinfo=datetime.timezone.utc)),
        ),
    ]
