# Generated by Django 4.1.2 on 2023-08-17 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcare', '0007_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 17, 32, 51, 749816, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='category',
            field=models.CharField(choices=[('Medical Examination', 'Medical Examination'), ('Doctor Check', 'Doctor Check'), ('Check Up', 'Check-Up'), ('Result Analysis', 'Result Analysis')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Dieting', 'Dieting'), ('Excercise', 'Excercise')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 17, 32, 51, 749816, tzinfo=datetime.timezone.utc)),
        ),
    ]
